name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Kirpichyov.FriendlyJwt
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Kirpichyov.FriendlyJwt
      
    - name: Run Unit tests
      run: dotnet test src/Kirpichyov.FriendlyJwt.UnitTests/Kirpichyov.FriendlyJwt.UnitTests.csproj --verbosity normal
        /p:CollectCoverage=true
        /p:CoverletOutput=TestResults/
        /p:CoverletOutputFormat=lcov
        
    - name: Run Integration tests
      run: dotnet test src/Kirpichyov.FriendlyJwt.IntegrationsTests/Kirpichyov.FriendlyJwt.IntegrationsTests.csproj --verbosity normal
        /p:CollectCoverage=true
        /p:CoverletOutput=TestResults/
        /p:CoverletOutputFormat=lcov

    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: src/Kirpichyov.FriendlyJwt.UnitTests/TestResults/coverage.info 
